# numpy random(난수) 발생하기
- 빅데이터를 처리하면, 대량의 데이터를 처리해야 하며, 때로는 데이터를 생성시킬 필요가 있음 
- 데이터를 생성하는데 난수를 발생시켜서 실험데이터로 사용을 하기도 함 
- Numpy에서 0~1사이의 1차원부터 고차원배열로 난수를 발생시킴

<br>

### 함수
- np.random.seed(number) : 
    - number값을 기준으로 난수를 발생시키면 항상 동일한 값의 난수가 발생 
- np.random.rand(number) 
    - seed 값을 기준으로 number의 수만큼, 난수를 발생  
- np.random.randint(number1,number2,”size”=5 ) : 
    - number1과 number2 사이에서 5개의 값을 발생 
- np.randomint.rand(number1,number2,”size”=(5,2) ) : 
    - number1과 number2 사이에서 5 by 2 배열값을 발생 

In [4]:
#random number 발생 
import numpy as np

np.random.seed(1)
# 난수 생성기의 시드를 1로 설정 → 이후 나오는 난수 값들이 고정됨.

np.random.rand(4)
# np.random.rand(4)는 [0, 1) 범위에서 4개의 난수를 생성
# 이때, seed(1)을 설정했으므로, 실행할 때마다 같은 난수들이 생성됨.

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [5]:
np.random.seed(1)
np.random.rand(20)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01,
       2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01,
       4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01])

In [ ]:
np.random.rand(5,3) #5행 3열의 array로도 난수 생성 가능

array([[0.80074457, 0.96826158, 0.31342418],
       [0.69232262, 0.87638915, 0.89460666],
       [0.08504421, 0.03905478, 0.16983042],
       [0.8781425 , 0.09834683, 0.42110763],
       [0.95788953, 0.53316528, 0.69187711]])

In [ ]:
np.random.randint(1, 10, size=(4,4))
# np.random.randint(low, high, size)
#   low=1: 최소값 (포함) → 1부터 시작
#   high=10: 최대값 (미포함) → 10은 포함되지 않음 (1 ≤ 값 < 10)
#   size=(4,4): 4×4 크기의 배열 생성
#즉, 1 이상 9 이하 (1 ≤ 값 < 10)의 정수 난수 16개를 생성하여 4×4 행렬로 반환함.

array([[4, 1, 9, 7],
       [5, 6, 7, 3],
       [6, 8, 9, 5],
       [5, 8, 8, 5]])