# numpy의 다양한 함수

### np.arange
- 실수단위의 범위를 지원 
- numpy array 자료형을 반환함 
- numpy에서 수행하는 연산 연계가 가능함 
- ex) np.arange([start], stop, [step]) 

### range
- 정수 단위의 범위만 지원
- range iterator 자료형을 반환함
- ex) range([start], stop, [step])

In [ ]:
import numpy as np
np.arange(10) #0부터 10까지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10) #2부터 10까지 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 20, 3) #1부터 20까지 3씩 증가

array([ 1,  4,  7, 10, 13, 16, 19])

In [5]:
range(10)

range(0, 10)

In [6]:
range(0, 10, 2)

range(0, 10, 2)

In [ ]:
list(range(0, 10, 2)) 
# 0부터 10까지 2단위로 한 걸 list로 출력

[0, 2, 4, 6, 8]

In [ ]:
np.array(range(0, 10, 2))
# 0부터 10까지 2단위로 한 걸 array로 출력

array([0, 2, 4, 6, 8])

### linspace()
- 시작값부터 끝까지 균일한 간격으로 지정된 개수만큼의 배열을 생성
- numpy.linspace(start, stop, num=50)

### logspace()
- 로그 스케일로 데이터를 생성
- numpy.logspace(start, stop, num=50) 

### reshape()
- 데이터의 수는 유지하면서 배열의 차원과 형태를 바꾸는 함수
-  new_array = old_array.reshape(shape)

### flatten()
- 2차원 이상의 고차원 배열을 1차원 배열 변경
- new_array.flatten()

In [ ]:
np.linspace(0, 50, 20) 
#0부터 50까지 20개 만큼의 배열 생성성

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [ ]:
np.logspace(0, 10, 10)
#log 0부터 log 10까지 10개 만큼 데이터 생성

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [ ]:
#reshape 예제
old_data = np.arange(10)
old_data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new_data = old_data.reshape(2, 5)
new_data
# 1행이었던 old data를, 
# 2행 5열로 reshape 함.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
new_data = old_data.reshape(5,-1)
new_data
# 1행이었던 old data를, 
# 5행 -1열로 reshape 함.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# flatten 예제
new_data.flatten() #1행으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])