# numpy indexig과 splicing

- 파이썬 인덱싱 및 슬라이싱 기능과 동일 
- numpy도 특정한 요소를 추출하기 위해서 인덱스와 슬라이싱 
기능이 있음 
- 논리적인 인덱싱, 2차원 인덱싱이 가능함.

![indexing](./images/indexing1.png)


In [1]:
#논리적인 인덱싱
import numpy as np

a_array = np.array([[10,20,30],[40,50,60],[70,80,90]])
a_array > 50

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
a_array[a_array>30] # 30이 넘는 것만 다시 따로 array를 만들어

array([40, 50, 60, 70, 80, 90])

In [ ]:
a_array[:,2] # 2열 전체

array([30, 60, 90])

In [6]:
a_array[:,2] > 40 # 2열에 있는 요소 중 40 이상인 것만 논리적 indexing

array([False,  True,  True])

In [11]:
a_array[:] % 3 == 0 # 3의 배수만 출력

# 참고로 a_array[:]는 그냥 a_array와 같은 결과임. 
# 전체 array가 다 indexing 됨.

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [ ]:
a_array[a_array % 3 ==0] # 3의 배수인 것만 따로 array 1행으로 출력

array([30, 60, 90])